### ISSUE TITLE
Incorrect display "Amount" for any LP token transfer

### ISSUE THREAD

**Issue by letsgoustc** [Loopring/loopring-explorer#23]
You can take this as an example.

https://explorer.loopring.io/tx/18926-323

It should be 2147.5 instead of 2.1475e-7. Looks like it does not count for the decimal.

**Comment by shad-k** [comment]
This is because the subgraph currently reports the wrong decimal count for LP tokens. This should be fixed on the subgraph, if possible.

For now retrieving the LP token data from https://api3.loopring.io/api/v3/exchange/tokens. This is included in https://github.com/Loopring/loopring-explorer/pull/28 . But this only fixes this for Transfer transactions.
Let me know if this needs to be fixed in other transaction types as well.
